spring:
  application:
    name: employee-service
  config:
    import: "optional:configserver:"
  datasource:
    url: jdbc:postgresql://postgres:5432/employeedb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  redis:
    host: redis
    port: 6379
  cloud:
    stream:
      function:
        definition: employeeCreatedPublisher
      bindings:
        employeeCreated-out-0:
          destination: employee-created-topic
          content-type: application/json
      default-binder: redis

server:
  port: 8201

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
