spring:
  application:
    name: employee-service

  config:
    import: "optional:configserver:"

  datasource:
    url: jdbc:postgresql://localhost:5432/employeedb
    username: postgres
    password: Teenwolf
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  cloud:
    compatibility-verifier:
      enabled: false
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: localhost:9092     # Change to kafka:9092 if running inside Docker
      function:
        definition: employeeCreatedPublisher
      bindings:
        employeeCreated-out-0:
          destination: employee-created-topic
          content-type: application/json

server:
  port: 8201

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
