spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: discovery-service
server:
  port: 8761
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
