spring:
  cache:
    type: caffeine
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
     routes:
      filters:
            - RemoveRequestHeader=Cookie
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

darum:
  ems:
    app:
      jwtsecret: afYx1C2rD8KpZt0vWq9nJ5eRbGsU3mTfXh4pA7sLdV0yN6oQjE1cH8kRzPwB2uF+
