spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:"
  datasource:
    url: jdbc:postgresql://postgres:5432/authdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  redis:
    host: redis
    port: 6379
  cloud:
    stream:
      function:
        definition: employeeCreated
      bindings:
        employeeCreated-in-0:
          destination: employee-created-topic
          group: auth-service
          content-type: application/json
      default-binder: redis

server:
  port: 8101

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

darum:
  ems:
    app:
      jwtsecret: afYx1C2rD8KpZt0vWq9nJ5eRbGsU3mTfXh4pA7sLdV0yN6oQjE1cH8kRzPwB2uF+
